[options]
girs_dir = "gir-files"
library = "GstMpegts"
version = "1.0"
min_cfg_version = "1.12"
target_path = "gstreamer-mpegts-sys"
work_mode = "sys"

external_libraries = [
    "GLib",
    "GObject",
    "Gst",
]
