[options]
girs_dir = "gir-files"
library = "GstSdp"
version = "1.0"
min_cfg_version = "1.0"
target_path = "gstreamer-sdp-sys"
work_mode = "sys"

external_libraries = [
    "GLib",
    "GObject"
]

[external_libraries]
gstreamer="Gst"
